[general]
debug = no

[kro-en]
url = ws://localhost:6006
sample_rate = 16000
callback_url = ws://127.0.0.1:8000
; result_mode = none|text|json
result_mode = text
; channel_mode = ro|wo|rw
channel_mode = wo

[kro-bg]
url = ws://localhost:6007

[kro-en-api]
url = wss://app.kroko.ai/api/v1/transcripts/streaming
apiKey = apiKey-from-kroko.ai
lang = en-US
;endpoints = false
result_mode = json
channel_mode = wo