[globals]

[sip-test]
; to Kroko API GW with ENG models
exten => _8881,1,NoOp()
same => n,Answer()
same => n,SpeechCreate(kro-en-api)
same => n,SpeechBackground(hello-world)
same => n,Verbose(0,${SPEECH_TEXT(0)})
same => n,Hangup()

; to Kroko ASR server with ENG models
exten => _8882,1,NoOp()
same => n,Answer()
same => n,SpeechCreate(kro-en)
same => n,SpeechBackground(hello-world)
same => n,Verbose(0,${SPEECH_TEXT(0)})
same => n,Hangup()

; to Kroko ASR server with ENG models
exten => _8883,1,NoOp()
same => n,Answer()
same => n,KrokoAudioHook(kro-en)
same => n,Playback(viki_test)
same => n,Hangup()

; to Kroko API GW with ENG models
exten => _8884,1,NoOp()
same => n,Answer()
same => n,KrokoAudioHook(kro-en-api)
same => n,Playback(viki_test)
same => n,Hangup()

exten => _9999,1,Answer(500)
exten => _9999,n,Echo()

exten => 1107,1,Set(PJSIP_HEADER(add,X-MyHeader)=newvalue)
exten => 1107,n,Dial(PJSIP/1107,15)
exten => 1107,n,Hangup()

exten => 1108,1,noop
same => n,Dial(PJSIP/1108,15)
same => n,Voicemail(${EXTEN}@dk-test,u)
same => n,Hangup()

exten => 1109,1,Set(CHANNEL(secure_bridge_media)=1)
exten => 1109,n,Dial(PJSIP/1109,15)
exten => 1109,n,Hangup()

exten => 1110,1,Set(CHANNEL(secure_bridge_media)=1)
exten => 1110,n,Dial(PJSIP/1110,15)
exten => 1110,n,Hangup()

